# Generated by Django 4.1.7 on 2024-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimaBlend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_sub',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
