# Generated by Django 4.1.7 on 2024-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimaBlend', '0002_alter_episode_video_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_dub',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
