# Generated by Django 4.1.7 on 2024-09-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimaBlend', '0003_alter_episode_options_alter_episode_video_dub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='total_episodes',
        ),
        migrations.AlterField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='AnimaBlend.anime'),
        ),
    ]
