# Generated by Django 4.1.7 on 2024-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimaBlend', '0004_remove_anime_total_episodes_alter_episode_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='wallpaper',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
