# Generated by Django 4.1.7 on 2024-11-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimaBlend', '0005_anime_wallpaper'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anime',
            table='animablend_anime',
        ),
        migrations.AlterModelTable(
            name='episode',
            table='animablend_episode',
        ),
    ]
